language: node_js
node_js:
  - "8"
env:
  - CXX=g++-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7
      - ldap-utils
      - slapd
      - libldap2-dev

before_script:
  - sudo service slapd stop 
  - sudo rm -R /etc/ldap/slapd.d/
  - sudo mkdir /etc/ldap/slapd.d/
  - sudo slapadd  /etc/ldap/slapd.d/ -n 0 -l ./test/test_tool/n0config.ldif
  - sudo cp ./test/test_tool/cacert.pem /etc/ssl/certs/
  - sudo cp ./test/test_tool/ldap01_slapd_cert.pem /etc/ssl/certs/
  - sudo cp ./test/test_tool/ldap01_slapd_key.pem /etc/ssl/private/
  - sudo chmod 777 -R /etc/ldap/
  - sudo service slapd restart
  - ldapadd -D cn=admin,dc=demoApp,dc=com -w secret -f ./light_db.ldif -c
  - ldapsearch -D cn=admin,dc=demoApp,dc=com -w secret -b dc=demoApp,dc=com
  - npm run addData